# Frontend extension (JS)
WEB_DIRECTORY = "./js"

# Python nodes
from .nodes.FPTextCleanAndSplitt import NODE_CLASS_MAPPINGS as FPTSTATE_MAPPINGS
from .nodes.FPTextCleanAndSplitt import NODE_DISPLAY_NAME_MAPPINGS as FPTSTATE_DISPLAY

from .nodes.FPFoldedPrompts import NODE_CLASS_MAPPINGS as FPFSTATE_MAPPINGS
from .nodes.FPFoldedPrompts import NODE_DISPLAY_NAME_MAPPINGS as FPFSTATE_DISPLAY

from .nodes.FPTextAreaPlus import NODE_CLASS_MAPPINGS as FPTPSTATE_MAPPINGS
from .nodes.FPTextAreaPlus import NODE_DISPLAY_NAME_MAPPINGS as FPTPSTATE_DISPLAY

NODE_CLASS_MAPPINGS = {
    **FPFSTATE_MAPPINGS,
    **FPTSTATE_MAPPINGS,
    **FPTPSTATE_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **FPFSTATE_DISPLAY,
    **FPTSTATE_DISPLAY,
    **FPTPSTATE_DISPLAY,
}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
